---
- hosts: dots
  become: yes
  tasks:
    - name: Create .config folder structure
      ansible.builtin.copy:
        backup: yes
        dest: "/home/preese/"
        src: "/home/preese//Work/dots-deploy/dotfiles/.config"

    - name: Create data folder structure
      ansible.builtin.copy:
        backup: yes
        dest: "/home/preese/"
        src: "/home/preese/Work/dots-deploy/dotfiles/{{ item }}"
      loop :
        - .bash_profile
        - .bashrc
        - .vimrc
        - .ssh

    - name: Add a few generally needed repos to new systems
      ansible.builtin.dnf:
        name:
          - "{{ item }}"
        state: present
      loop:
       - wget
       - neofetch
       - inxi
       - htop
       - exa
       - fd-find
       - bat
      when: ansible_facts['distribution'] == "Fedora"



