---
- name: Set some states
  hosts: dots
  gather_facts: false
  become: true

  tasks:

    - name: Check script
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: true

    - name: Create .config folder structure
      ansible.builtin.copy:
        backup: true
        dest: "/home/preese/"
        src: "/home/preese/Work/ansible/dots-deploy/dotfiles/.config"
        owner: preese
        group: preese
        mode: '0755'

    - name: Create data folder structure
      ansible.builtin.copy:
        backup: true
        dest: "/home/preese/"
        src: "/home/preese/Work/ansible/dots-deploy/dotfiles/{{ item }}"
        owner: preese
        group: preese
        mode: '0644'
      loop:
        - .bash_profile
        - .bashrc
        - .vimrc
        - .ssh

    - name: add 2 iperf3 systemd files
      ansible.builtin.copy:
        dest: "/etc/systemd/system/"
        src: "/home/preese/Work/ansible/dots-deploy/iperf3d/"
        owner: root
        group: root
        mode: '0755'

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start two iperf3 daemons as a service 
      ansible.builtin.systemd:
        name: iperf3
        state: started
        enabled: true

    - name: Start two iperf3 daemons as a user service 
      ansible.builtin.systemd:
        name: iperf3-02
        state: started
        enabled: true

    - name: Add a few generally needed repos to new systems
      ansible.builtin.dnf:
        name:
          - "{{ item }}"
        state: present
      loop:
        - dnf-automatic
        - ethtool
        - wget
        - tar
        - dua-cli
        - neofetch
        - inxi
        - htop
        - exa
        - fd-find
        - bat
        - source-foundry-hack-fonts

    - name: Create data folder structure
      ansible.builtin.copy:
        dest: "/etc/dnf/"
        src: "/home/preese/Work/ansible/dots-deploy/dotfiles/automatic.conf"
        owner: root
        group: root
        mode: '0644'
        backup: false

    - name: Enable service dnf-automatic
      ansible.builtin.service:
        name: dnf-automatic.timer
        enabled: true
        state: started
