---
- hosts: dots
  become: yes
  tasks:
    - name: Create .config folder structure
      ansible.builtin.copy:
        backup: yes
        dest: "/home/preese/"
        src: "/home/preese/Work/ansible/dots-deploy/dotfiles/.config"
        follow: yes

    - name: Create data folder structure
      ansible.builtin.copy:
        backup: yes
        dest: "/home/preese/"
        src: "/home/preese/Work/ansible/dots-deploy/dotfiles/{{ item }}"
      loop :
        - .bash_profile
        - .bashrc
        - .vimrc
        - .ssh

    - name: Add a few generally needed repos to new systems
      ansible.builtin.dnf:
        name:
          - "{{ item }}"
        state: present
      loop:
       - dnf-automatic
       - wget
       - neofetch
       - inxi
       - htop
       - exa
       - fd-find
       - bat
      when: ansible_facts['distribution'] == "Fedora"

    - name: Create data folder structure
      ansible.builtin.copy:
        dest: "/etc/dnf/"
        src: "/home/preese/Work/ansible/dots-deploy/dotfiles/automatic.conf"
        owner: root
        group: root
        mode: '0644'
        backup: no

    - name: Enable service dnf-automatic
      ansible.builtin.service:
        name: dnf-automatic.timer
        enabled: yes
        state: started



