---
- name: Set some states
  hosts: dots
  gather_facts: false
  become: true

  tasks:

    - name: Check script
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: true

    - name: Create .config folder structure
      ansible.builtin.copy:
        backup: true
        dest: "/home/preese/"
        src: "/home/preese/Work/ansible/dots-deploy/dotfiles/.config"
        owner: preese
        group: preese
        mode: '0755'

    - name: Create data folder structure
      ansible.builtin.copy:
        backup: true
        dest: "/home/preese/"
        src: "/home/preese/Work/ansible/dots-deploy/dotfiles/{{ item }}"
        owner: preese
        group: preese
        mode: '0644'
      loop:
        - .bash_profile
        - .bashrc
        - .vimrc
        - .ssh

    - name: make bin dir in home dir
      ansible.builtin.copy:
        dest: "/home/preese/"
        src: "/home/preese/Work/ansible/dots-deploy/bin/"
        owner: preese
        group: preese
        mode: '0755'

    - name: add krestart.sh to $HOME/bin dir
      ansible.builtin.copy:
        dest: "/home/preese/bin/"
        src: "/home/preese/Work/ansible/dots-deploy/bin/krestart.sh"
        owner: preese
        group: preese
        mode: '0755'

    - name: add 2 iperf3 systemd files
      ansible.builtin.copy:
        dest: "/etc/systemd/system/"
        src: "/home/preese/Work/ansible/dots-deploy/iperf3d/"
        owner: root
        group: root
        mode: '0755'

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Add a few generally needed repos to new systems
      ansible.builtin.dnf:
        name:
          - "{{ item }}"
        state: present
      loop:
        - bat
        - cockpit
        - cockpit-machines
        - cockpit-networkmanager
        - cockpit-packagekit
        - cockpit-selinux
        - dnf-automatic
        - dua-cli
        - ethtool
        - exa
        - fd-find
        - htop
        - inxi
        - iperf3
        - neofetch
        - source-foundry-hack-fonts
        - tar
        - wget

    - name: Start two iperf3 daemons as a service 
      ansible.builtin.systemd:
        name: iperf3
        state: started
        enabled: true

    - name: Start two iperf3 daemons as a user service 
      ansible.builtin.systemd:
        name: iperf3-02
        state: started
        enabled: true

    - name: Enable port 5201-5202 for iperf3 daemons
      ansible.posix.firewalld:
        zone: public
        port: 5201-5202/tcp
        permanent: true
        immediate: true
        state: enabled

    - name: Enable port 9090 to be in public zone
      ansible.posix.firewalld:
        zone: public
        service: cockpit
        permanent: true
        immediate: true
        state: enabled

    - name: Create data folder structure
      ansible.builtin.copy:
        dest: "/etc/dnf/"
        src: "/home/preese/Work/ansible/dots-deploy/dotfiles/automatic.conf"
        owner: root
        group: root
        mode: '0644'
        backup: false

    - name: Enable service dnf-automatic
      ansible.builtin.service:
        name: dnf-automatic.timer
        enabled: true
        state: started
